services:
  steampipe:
    build: .
    container_name: steampipe-aws
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    ports:
      - "9193:9193"
    volumes:
      - steampipe_data:/home/steampipe/.steampipe
    restart: unless-stopped

volumes:
  steampipe_data: